import type { Board, Comment, Notification, Post } from "@/lib/types";

export const demoBoards: Board[] = [
  {
    id: "board-humor",
    slug: "humor",
    name: "ユーモア",
    description: "ジョークやミーム、日常の笑いを気軽に共有するボードです。",
    icon: "sentiment_very_satisfied",
    sort_order: 1,
    is_active: true,
    post_count: 12840,
  },
  {
    id: "board-news",
    slug: "news",
    name: "ニュース",
    description:
      "国内外の最新ニュースについて、じっくり意見を交わすボードです。",
    icon: "newspaper",
    sort_order: 2,
    is_active: true,
    post_count: 9432,
  },
  {
    id: "board-sports",
    slug: "sports",
    name: "スポーツ",
    description: "試合速報、分析、移籍情報、勝敗予想を楽しむボードです。",
    icon: "sports_soccer",
    sort_order: 3,
    is_active: true,
    post_count: 7218,
  },
  {
    id: "board-game",
    slug: "game",
    name: "ゲーム",
    description: "ゲーム、ハードウェア、新作、攻略情報を共有するボードです。",
    icon: "sports_esports",
    sort_order: 4,
    is_active: true,
    post_count: 6884,
  },
];

const now = Date.now();
const iso = (hours: number) => new Date(now - hours * 3_600_000).toISOString();

export const demoPosts: Post[] = [
  {
    id: "welcome",
    post_number: 1,
    board_id: "board-humor",
    board: {
      slug: "humor",
      name: "ユーモア",
      icon: "sentiment_very_satisfied",
    },
    author_id: "admin",
    author: { username: "Admin_Panmoa", avatar_url: null },
    guest_name: null,
    title: "コミュニティガイドライン：投稿前にお読みください",
    content:
      "Panmoaへようこそ。相手を尊重し、話題に沿って交流してください。すべてのユーザー名の向こう側には、一人の人がいます。\n\n分かりやすいタイトルを付け、引用元を明記し、ルール違反のコンテンツは報告してください。",
    thumbnail_url: null,
    view_count: 12040,
    comment_count: 42,
    vote_count: 986,
    is_pinned: true,
    is_notice: true,
    created_at: iso(72),
    updated_at: iso(72),
  },
  {
    id: "cat-chef",
    post_number: 6,
    board_id: "board-humor",
    board: {
      slug: "humor",
      name: "ユーモア",
      icon: "sentiment_very_satisfied",
    },
    author_id: "catlover",
    author: { username: "CatLover99", avatar_url: null },
    guest_name: null,
    title: "うちの猫、自分をプロの料理人だと思っている",
    content:
      "毎晩まな板の隣に座り、小さくて厳しい総料理長のように夕食作りを監督しています。今日はパセリにダメ出しされました。",
    thumbnail_url:
      "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=480&q=80",
    view_count: 2410,
    comment_count: 15,
    vote_count: 4210,
    is_pinned: false,
    is_notice: false,
    created_at: iso(1),
    updated_at: iso(1),
  },
  {
    id: "remote-pajamas",
    post_number: 5,
    board_id: "board-humor",
    board: {
      slug: "humor",
      name: "ユーモア",
      icon: "sentiment_very_satisfied",
    },
    author_id: "remote",
    author: { username: "RemoteWorker", avatar_url: null },
    guest_name: null,
    title: "パジャマで在宅勤務するという矛盾",
    content:
      "通勤距離はたった4メートルなのに、なぜか今日も2分遅刻しました。科学でも説明できません。",
    thumbnail_url: null,
    view_count: 1140,
    comment_count: 8,
    vote_count: 892,
    is_pinned: false,
    is_notice: false,
    created_at: iso(3),
    updated_at: iso(3),
  },
  {
    id: "captcha",
    post_number: 4,
    board_id: "board-humor",
    board: {
      slug: "humor",
      name: "ユーモア",
      icon: "sentiment_very_satisfied",
    },
    author_id: "human",
    author: { username: "DefinitelyHuman", avatar_url: null },
    guest_name: null,
    title: "CAPTCHA、最近難しくなっていませんか？",
    content: "信号機が3ピクセルしかなく、もはや哲学的な概念に見えてきました。",
    thumbnail_url: null,
    view_count: 8700,
    comment_count: 124,
    vote_count: 3200,
    is_pinned: false,
    is_notice: false,
    created_at: iso(6),
    updated_at: iso(6),
  },
  {
    id: "launch",
    post_number: 3,
    board_id: "board-news",
    board: { slug: "news", name: "ニュース", icon: "newspaper" },
    author_id: "editor",
    author: { username: "Newsroom", avatar_url: null },
    guest_name: null,
    title: "Panmoa 2.0公開：新しい議論の時代へ",
    content:
      "新しいアーキテクチャでは、すばやく整理された議論を最優先にしました。ボードは動的になり、ナビゲーションも分かりやすく、情報量を保ちながら視覚的なノイズを抑えています。",
    thumbnail_url:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=960&q=80",
    view_count: 16200,
    comment_count: 87,
    vote_count: 5840,
    is_pinned: false,
    is_notice: false,
    created_at: iso(12),
    updated_at: iso(12),
  },
  {
    id: "framework-poll",
    post_number: 2,
    board_id: "board-game",
    board: { slug: "game", name: "ゲーム", icon: "sports_esports" },
    author_id: "dev",
    author: { username: "StackWatcher", avatar_url: null },
    guest_name: null,
    title: "今日の投票：いま最も重視しているフレームワークは？",
    content:
      "何を開発しているのか、チームがその選択をした理由も教えてください。",
    thumbnail_url: null,
    view_count: 3780,
    comment_count: 64,
    vote_count: 1190,
    is_pinned: false,
    is_notice: false,
    created_at: iso(20),
    updated_at: iso(20),
  },
];

export const demoComments: Comment[] = [
  {
    id: "comment-1",
    post_id: "cat-chef",
    author_id: "remote",
    author: { username: "RemoteWorker", avatar_url: null },
    guest_name: null,
    parent_id: null,
    content: "盛り付けが完璧だとシェフにお伝えください。",
    created_at: iso(0.6),
  },
  {
    id: "comment-2",
    post_id: "cat-chef",
    author_id: "catlover",
    author: { username: "CatLover99", avatar_url: null },
    guest_name: null,
    parent_id: "comment-1",
    content: "お褒めの言葉を受け取り、報酬としてマグロを1匹ご希望です。",
    created_at: iso(0.3),
  },
];

export const demoNotifications: Notification[] = [
  {
    id: "notification-vote-1",
    recipient_id: "admin",
    actor_id: "catlover",
    actor: { username: "CatLover99", avatar_url: null },
    actor_name: null,
    type: "vote",
    post_id: "welcome",
    post: {
      title: "コミュニティガイドライン：投稿前にお読みください",
      board: { slug: "humor" },
    },
    comment_id: null,
    is_read: false,
    created_at: iso(0.2),
  },
  {
    id: "notification-comment-1",
    recipient_id: "catlover",
    actor_id: "remote",
    actor: { username: "RemoteWorker", avatar_url: null },
    actor_name: null,
    type: "comment",
    post_id: "cat-chef",
    post: {
      title: "うちの猫、自分をプロの料理人だと思っている",
      board: { slug: "humor" },
    },
    comment_id: "comment-1",
    is_read: true,
    created_at: iso(0.6),
  },
];
