import type { Board, Comment, Post } from "@/lib/types";

export const demoBoards: Board[] = [
  {
    id: "board-humor",
    slug: "humor",
    name: "Humor",
    description: "A light place for sharp jokes, memes, and everyday comedy.",
    icon: "sentiment_very_satisfied",
    sort_order: 1,
    is_active: true,
    post_count: 12840,
  },
  {
    id: "board-news",
    slug: "news",
    name: "News",
    description:
      "Breaking stories and considered discussion from around the world.",
    icon: "newspaper",
    sort_order: 2,
    is_active: true,
    post_count: 9432,
  },
  {
    id: "board-sports",
    slug: "sports",
    name: "Sports",
    description: "Live games, analysis, transfers, and community predictions.",
    icon: "sports_soccer",
    sort_order: 3,
    is_active: true,
    post_count: 7218,
  },
  {
    id: "board-game",
    slug: "game",
    name: "Game",
    description: "Games, hardware, releases, guides, and friendly competition.",
    icon: "sports_esports",
    sort_order: 4,
    is_active: true,
    post_count: 6884,
  },
];

const now = Date.now();
const iso = (hours: number) => new Date(now - hours * 3_600_000).toISOString();

export const demoPosts: Post[] = [
  {
    id: "welcome",
    board_id: "board-humor",
    board: { slug: "humor", name: "Humor", icon: "sentiment_very_satisfied" },
    author_id: "admin",
    author: { username: "Admin_Panmoa", avatar_url: null },
    title: "Community Rules: Please read before posting",
    content:
      "Welcome to Panmoa. Be generous, stay on topic, and remember there is a person behind every username.\n\nUse clear titles, credit original creators, and report content that breaks the rules.",
    thumbnail_url: null,
    view_count: 12040,
    comment_count: 42,
    vote_count: 986,
    is_pinned: true,
    is_notice: true,
    created_at: iso(72),
    updated_at: iso(72),
  },
  {
    id: "cat-chef",
    board_id: "board-humor",
    board: { slug: "humor", name: "Humor", icon: "sentiment_very_satisfied" },
    author_id: "catlover",
    author: { username: "CatLover99", avatar_url: null },
    title: "My cat thinks he's a professional chef",
    content:
      "He sits beside the cutting board every evening and supervises dinner like the smallest, strictest executive chef. Today he rejected the parsley.",
    thumbnail_url:
      "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=480&q=80",
    view_count: 2410,
    comment_count: 15,
    vote_count: 4210,
    is_pinned: false,
    is_notice: false,
    created_at: iso(1),
    updated_at: iso(1),
  },
  {
    id: "remote-pajamas",
    board_id: "board-humor",
    board: { slug: "humor", name: "Humor", icon: "sentiment_very_satisfied" },
    author_id: "remote",
    author: { username: "RemoteWorker", avatar_url: null },
    title: "The paradox of working from home in pajamas",
    content:
      "The commute is four metres, yet somehow I am still two minutes late. Science has no explanation.",
    thumbnail_url: null,
    view_count: 1140,
    comment_count: 8,
    vote_count: 892,
    is_pinned: false,
    is_notice: false,
    created_at: iso(3),
    updated_at: iso(3),
  },
  {
    id: "captcha",
    board_id: "board-humor",
    board: { slug: "humor", name: "Humor", icon: "sentiment_very_satisfied" },
    author_id: "human",
    author: { username: "DefinitelyHuman", avatar_url: null },
    title: "Is it just me or are captchas getting harder?",
    content:
      "At this point the traffic light is three pixels and a philosophical concept.",
    thumbnail_url: null,
    view_count: 8700,
    comment_count: 124,
    vote_count: 3200,
    is_pinned: false,
    is_notice: false,
    created_at: iso(6),
    updated_at: iso(6),
  },
  {
    id: "launch",
    board_id: "board-news",
    board: { slug: "news", name: "News", icon: "newspaper" },
    author_id: "editor",
    author: { username: "Newsroom", avatar_url: null },
    title: "Panmoa 2.0 Launch: A New Era for Professional Discussion",
    content:
      "Our new architecture puts fast, structured discussion first. Boards are now dynamic, navigation is clearer, and every page is designed for information density without visual noise.",
    thumbnail_url:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=960&q=80",
    view_count: 16200,
    comment_count: 87,
    vote_count: 5840,
    is_pinned: false,
    is_notice: false,
    created_at: iso(12),
    updated_at: iso(12),
  },
  {
    id: "framework-poll",
    board_id: "board-game",
    board: { slug: "game", name: "Game", icon: "sports_esports" },
    author_id: "dev",
    author: { username: "StackWatcher", avatar_url: null },
    title: "Poll of the Day: Which framework are you prioritizing?",
    content: "Share what you are building and why your team made the choice.",
    thumbnail_url: null,
    view_count: 3780,
    comment_count: 64,
    vote_count: 1190,
    is_pinned: false,
    is_notice: false,
    created_at: iso(20),
    updated_at: iso(20),
  },
];

export const demoComments: Comment[] = [
  {
    id: "comment-1",
    post_id: "cat-chef",
    author_id: "remote",
    author: { username: "RemoteWorker", avatar_url: null },
    parent_id: null,
    content: "Please tell the chef that the plating is impeccable.",
    created_at: iso(0.6),
  },
  {
    id: "comment-2",
    post_id: "cat-chef",
    author_id: "catlover",
    author: { username: "CatLover99", avatar_url: null },
    parent_id: "comment-1",
    content: "He accepts your compliment and requests one tuna as payment.",
    created_at: iso(0.3),
  },
];
