import type {
  Board,
  ChargingReview,
  Comment,
  Notification,
  OwnershipCost,
  Post,
  PriceReport,
} from "@/lib/types";

export const demoBoards: Board[] = [
  {
    id: "board-tesla",
    slug: "tesla",
    name: "Teslaオーナー",
    description:
      "充電、保険、整備、維持費など、Teslaオーナーの実体験を共有する掲示板です。",
    icon: "electric_car",
    sort_order: 1,
    is_active: true,
    post_count: 18,
  },
  {
    id: "board-tesla-buying",
    slug: "tesla-buying",
    name: "購入相談",
    description:
      "モデル選び、補助金、納期、中古車など、Tesla購入前の疑問を相談する掲示板です。",
    icon: "shopping_cart",
    sort_order: 2,
    is_active: true,
    post_count: 9,
  },
];

const now = Date.now();
const iso = (hours: number) => new Date(now - hours * 3_600_000).toISOString();
const dateIso = (hours: number) => iso(hours).slice(0, 10);

export const demoPosts: Post[] = [
  {
    id: "welcome",
    post_number: 1,
    board_id: "board-tesla",
    board: {
      slug: "tesla",
      name: "Teslaオーナー",
      icon: "electric_car",
    },
    author_id: "admin",
    author: { username: "Panmoa編集部", avatar_url: null },
    guest_name: null,
    title: "実体験を共有するときのガイドライン",
    content:
      "充電速度、費用、走行距離などは、計測した時期や条件も一緒に書いてください。公式情報を引用するときは参照URLを添え、推測と事実を分けて共有しましょう。",
    thumbnail_url: null,
    view_count: 842,
    comment_count: 0,
    vote_count: 56,
    is_pinned: true,
    is_notice: true,
    created_at: iso(72),
    updated_at: iso(72),
  },
  {
    id: "charging-tokyo",
    post_number: 6,
    board_id: "board-tesla",
    board: {
      slug: "tesla",
      name: "Teslaオーナー",
      icon: "electric_car",
    },
    author_id: "model3-tokyo",
    author: { username: "Model3東京", avatar_url: null },
    guest_name: null,
    title: "都内スーパーチャージャー、平日夜の待ち時間を共有しませんか",
    content:
      "平日夜に利用した充電スポットの混雑状況を比較したいです。訪問時間、待ち時間、実測した最大充電速度が分かる方は条件と一緒に教えてください。",
    thumbnail_url: null,
    view_count: 324,
    comment_count: 2,
    vote_count: 31,
    is_pinned: false,
    is_notice: false,
    created_at: iso(1),
    updated_at: iso(1),
  },
  {
    id: "model-y-winter",
    post_number: 5,
    board_id: "board-tesla",
    board: {
      slug: "tesla",
      name: "Teslaオーナー",
      icon: "electric_car",
    },
    author_id: "snow-driver",
    author: { username: "雪国ModelY", avatar_url: null },
    guest_name: null,
    title: "寒冷地のModel Y、冬季電費を比較したいです",
    content:
      "気温、タイヤ、暖房設定で電費が大きく変わるため、同じ条件に近い実測値を集めたいです。北海道・東北で冬を越した方の記録をお願いします。",
    thumbnail_url: null,
    view_count: 418,
    comment_count: 0,
    vote_count: 44,
    is_pinned: false,
    is_notice: false,
    created_at: iso(3),
    updated_at: iso(3),
  },
  {
    id: "maintenance-cost",
    post_number: 4,
    board_id: "board-tesla",
    board: {
      slug: "tesla",
      name: "Teslaオーナー",
      icon: "electric_car",
    },
    author_id: "long-range-owner",
    author: { username: "LRオーナー", avatar_url: null },
    guest_name: null,
    title: "3年目点検までに実際にかかった消耗品費",
    content:
      "タイヤ、ワイパー、エアコンフィルターなど、車検前までに発生した費用を項目別に整理しています。走行距離別の比較にも使えるよう更新します。",
    thumbnail_url: null,
    view_count: 736,
    comment_count: 0,
    vote_count: 68,
    is_pinned: false,
    is_notice: false,
    created_at: iso(8),
    updated_at: iso(8),
  },
  {
    id: "insurance-quote",
    post_number: 3,
    board_id: "board-tesla-buying",
    board: {
      slug: "tesla-buying",
      name: "購入相談",
      icon: "shopping_cart",
    },
    author_id: null,
    guest_name: "購入検討中",
    title: "Model 3とModel Yの保険料、見積もり条件の違いを知りたい",
    content:
      "車両保険を付けた場合の差を比較しています。年齢、等級、地域、年間走行距離によってどの程度変わったか教えてください。",
    thumbnail_url: null,
    view_count: 289,
    comment_count: 0,
    vote_count: 24,
    is_pinned: false,
    is_notice: false,
    created_at: iso(12),
    updated_at: iso(12),
  },
  {
    id: "used-model-y",
    post_number: 2,
    board_id: "board-tesla-buying",
    board: {
      slug: "tesla-buying",
      name: "購入相談",
      icon: "shopping_cart",
    },
    author_id: null,
    guest_name: "中古車検討",
    title: "中古Model Yで確認しておきたい項目は？",
    content:
      "保証の残期間、タイヤ、充電履歴などを確認する予定です。購入経験者が実車確認で重視した点や、納車後に気付いた点を知りたいです。",
    thumbnail_url: null,
    view_count: 351,
    comment_count: 0,
    vote_count: 37,
    is_pinned: false,
    is_notice: false,
    created_at: iso(20),
    updated_at: iso(20),
  },
];

export const demoComments: Comment[] = [
  {
    id: "comment-1",
    post_id: "charging-tokyo",
    author_id: "model-y-owner",
    author: { username: "ModelY横浜", avatar_url: null },
    guest_name: null,
    parent_id: null,
    content:
      "訪問時刻とバッテリー残量も一緒に記録すると、速度差を比較しやすそうです。",
    created_at: iso(0.6),
  },
  {
    id: "comment-2",
    post_id: "charging-tokyo",
    author_id: "model3-tokyo",
    author: { username: "Model3東京", avatar_url: null },
    guest_name: null,
    parent_id: "comment-1",
    content: "ありがとうございます。次回から到着時SOCも記録します。",
    created_at: iso(0.3),
  },
];

export const demoNotifications: Notification[] = [
  {
    id: "notification-vote-1",
    recipient_id: "admin",
    actor_id: "model3-tokyo",
    actor: { username: "Model3東京", avatar_url: null },
    actor_name: null,
    type: "vote",
    post_id: "welcome",
    post: {
      title: "実体験を共有するときのガイドライン",
      board: { slug: "tesla" },
    },
    comment_id: null,
    is_read: false,
    created_at: iso(0.2),
  },
  {
    id: "notification-comment-1",
    recipient_id: "model3-tokyo",
    actor_id: "model-y-owner",
    actor: { username: "ModelY横浜", avatar_url: null },
    actor_name: null,
    type: "comment",
    post_id: "charging-tokyo",
    post: {
      title: "都内スーパーチャージャー、平日夜の待ち時間を共有しませんか",
      board: { slug: "tesla" },
    },
    comment_id: "comment-1",
    is_read: true,
    created_at: iso(0.6),
  },
];

export const demoChargingReviews: ChargingReview[] = [
  {
    id: "charging-review-1",
    author_id: "model3-tokyo",
    author: { username: "Model3東京", avatar_url: null },
    location_name: "東京ベイ スーパーチャージャー",
    prefecture: "東京都",
    charger_type: "supercharger",
    max_power_kw: 250,
    measured_speed_kw: 181,
    wait_minutes: 5,
    congestion: "busy",
    rating: 4,
    visited_on: dateIso(36),
    notes: "平日19時台。到着時SOC 18%、4基中3基を利用中でした。",
    created_at: iso(24),
  },
  {
    id: "charging-review-2",
    author_id: "model-y-owner",
    author: { username: "ModelY横浜", avatar_url: null },
    location_name: "横浜みなとみらい スーパーチャージャー",
    prefecture: "神奈川県",
    charger_type: "supercharger",
    max_power_kw: 250,
    measured_speed_kw: 164,
    wait_minutes: 0,
    congestion: "comfortable",
    rating: 5,
    visited_on: dateIso(72),
    notes: "休日午前。周辺施設を利用しやすく、待ち時間はありませんでした。",
    created_at: iso(48),
  },
  {
    id: "charging-review-3",
    author_id: "snow-driver",
    author: { username: "雪国ModelY", avatar_url: null },
    location_name: "札幌市内 公共急速充電器",
    prefecture: "北海道",
    charger_type: "public",
    max_power_kw: 90,
    measured_speed_kw: 62,
    wait_minutes: 12,
    congestion: "full",
    rating: 3,
    visited_on: dateIso(120),
    notes: "外気温-4℃、到着時SOC 27%。前車の終了を待って利用しました。",
    created_at: iso(96),
  },
];

export const demoOwnershipCosts: OwnershipCost[] = [
  {
    id: "ownership-cost-1",
    author_id: "long-range-owner",
    author: { username: "LRオーナー", avatar_url: null },
    model: "Model 3",
    model_year: 2023,
    mileage_km: 28600,
    category: "maintenance",
    amount_yen: 88000,
    occurred_on: dateIso(240),
    details: "4本のタイヤ交換。工賃と廃タイヤ処分費を含みます。",
    created_at: iso(216),
  },
  {
    id: "ownership-cost-2",
    author_id: "model-y-owner",
    author: { username: "ModelY横浜", avatar_url: null },
    model: "Model Y",
    model_year: 2024,
    mileage_km: 14200,
    category: "insurance",
    amount_yen: 126400,
    occurred_on: dateIso(720),
    details: "年間保険料。車両保険あり、20等級、年間走行距離1万km以下。",
    created_at: iso(696),
  },
  {
    id: "ownership-cost-3",
    author_id: "snow-driver",
    author: { username: "雪国ModelY", avatar_url: null },
    model: "Model Y",
    model_year: 2023,
    mileage_km: 31500,
    category: "accessory",
    amount_yen: 168000,
    occurred_on: dateIso(1440),
    details: "冬用タイヤとホイールのセット。装着費用を含みます。",
    created_at: iso(1416),
  },
];

export const demoPriceReports: PriceReport[] = [
  {
    id: "price-report-1",
    author_id: "model3-tokyo",
    author: { username: "Model3東京", avatar_url: null },
    report_type: "insurance",
    model: "Model 3",
    model_year: 2023,
    prefecture: "東京都",
    amount_yen: 118000,
    provider: "国内損害保険会社",
    observed_on: dateIso(168),
    details: "30代、20等級、車両保険ありの年間見積もり。",
    created_at: iso(144),
  },
  {
    id: "price-report-2",
    author_id: "model-y-owner",
    author: { username: "ModelY横浜", avatar_url: null },
    report_type: "subsidy",
    model: "Model Y",
    model_year: 2026,
    prefecture: "神奈川県",
    amount_yen: 1270000,
    provider: "CEV補助金",
    observed_on: dateIso(336),
    details: "国の補助金。申請時は登録日と予算残額の確認が必要です。",
    created_at: iso(312),
  },
  {
    id: "price-report-3",
    author_id: "long-range-owner",
    author: { username: "LRオーナー", avatar_url: null },
    report_type: "used_price",
    model: "Model 3",
    model_year: 2022,
    prefecture: "大阪府",
    amount_yen: 3280000,
    provider: "中古車販売店",
    observed_on: dateIso(96),
    details: "走行3.2万km、ロングレンジ、修復歴なしの店頭価格。",
    created_at: iso(72),
  },
];
