import type { Config } from "tailwindcss";

const config: Config = {
  theme: {
    extend: {
      colors: {
        surface: "#f8fafc",
        "surface-dim": "#e2e8f0",
        "surface-bright": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f8fafc",
        "surface-container": "#f1f5f9",
        "surface-container-high": "#e2e8f0",
        "surface-container-highest": "#cbd5e1",
        "on-surface": "#0f172a",
        "on-surface-variant": "#334155",
        "inverse-surface": "#0f172a",
        "inverse-on-surface": "#f8fafc",
        outline: "#64748b",
        "outline-variant": "#cbd5e1",
        "surface-tint": "#2563eb",
        primary: "#2563eb",
        "on-primary": "#ffffff",
        "primary-container": "#1d4ed8",
        "on-primary-container": "#eff6ff",
        "inverse-primary": "#93c5fd",
        secondary: "#15803d",
        "on-secondary": "#ffffff",
        "secondary-container": "#dcfce7",
        "on-secondary-container": "#166534",
        tertiary: "#c2410c",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#ffedd5",
        "on-tertiary-container": "#9a3412",
        error: "#dc2626",
        "on-error": "#ffffff",
        "error-container": "#fef2f2",
        "on-error-container": "#991b1b",
        "primary-fixed": "#eff6ff",
        "primary-fixed-dim": "#dbeafe",
        "on-primary-fixed": "#1e3a8a",
        "on-primary-fixed-variant": "#1d4ed8",
        "secondary-fixed": "#dcfce7",
        "secondary-fixed-dim": "#bbf7d0",
        "on-secondary-fixed": "#14532d",
        "on-secondary-fixed-variant": "#166534",
        "tertiary-fixed": "#ffedd5",
        "tertiary-fixed-dim": "#fed7aa",
        "on-tertiary-fixed": "#7c2d12",
        "on-tertiary-fixed-variant": "#9a3412",
        background: "#f8fafc",
        foreground: "#0f172a",
        card: "#ffffff",
        "card-foreground": "#0f172a",
        muted: "#f1f5f9",
        "muted-foreground": "#64748b",
        accent: "#eff6ff",
        "accent-foreground": "#1d4ed8",
        destructive: "#dc2626",
        "destructive-foreground": "#ffffff",
        border: "#e2e8f0",
        input: "#cbd5e1",
        ring: "#2563eb",
        "on-background": "#0f172a",
        "surface-variant": "#e2e8f0",
        "surface-alt": "#f8fafc",
        "success-light": "#f0fdf4",
        "border-subtle": "#e2e8f0",
        "text-muted": "#64748b",
      },
      fontFamily: {
        "headline-lg": ["var(--font-hanken)", "var(--font-noto-jp)"],
        "headline-lg-mobile": ["var(--font-hanken)", "var(--font-noto-jp)"],
        "headline-md": ["var(--font-hanken)", "var(--font-noto-jp)"],
        "body-lg": ["var(--font-inter)", "var(--font-noto-jp)"],
        "body-md": ["var(--font-inter)", "var(--font-noto-jp)"],
        "body-sm": ["var(--font-inter)", "var(--font-noto-jp)"],
        "label-md": ["var(--font-inter)", "var(--font-noto-jp)"],
        "label-sm": ["var(--font-inter)", "var(--font-noto-jp)"],
      },
      fontSize: {
        "headline-lg": [
          "32px",
          { lineHeight: "40px", fontWeight: "700", letterSpacing: "-0.02em" },
        ],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", fontWeight: "700", letterSpacing: "-0.02em" },
        ],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-md": [
          "13px",
          { lineHeight: "18px", fontWeight: "600", letterSpacing: "0" },
        ],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
      borderRadius: {
        sm: "0.375rem",
        DEFAULT: "0.5rem",
        md: "0.625rem",
        lg: "0.75rem",
        xl: "1rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        gutter: "16px",
        "margin-desktop": "24px",
        "container-max-width": "1200px",
      },
      maxWidth: { "container-max-width": "1200px" },
    },
  },
};

export default config;
