import type { Config } from "tailwindcss";

const config: Config = {
  theme: {
    extend: {
      colors: {
        surface: "#fbf9f8",
        "surface-dim": "#dcd9d9",
        "surface-bright": "#fbf9f8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0eded",
        "surface-container-high": "#eae8e7",
        "surface-container-highest": "#e4e2e1",
        "on-surface": "#1b1c1c",
        "on-surface-variant": "#434656",
        "inverse-surface": "#303030",
        "inverse-on-surface": "#f3f0f0",
        outline: "#737688",
        "outline-variant": "#c3c5d9",
        "surface-tint": "#004dea",
        primary: "#0041c8",
        "on-primary": "#ffffff",
        "primary-container": "#0055ff",
        "on-primary-container": "#e3e6ff",
        "inverse-primary": "#b6c4ff",
        secondary: "#006e0c",
        "on-secondary": "#ffffff",
        "secondary-container": "#8ff780",
        "on-secondary-container": "#00730d",
        tertiary: "#972500",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#c13301",
        "on-tertiary-container": "#ffe1d9",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#dce1ff",
        "primary-fixed-dim": "#b6c4ff",
        "on-primary-fixed": "#001551",
        "on-primary-fixed-variant": "#0039b3",
        "secondary-fixed": "#92fa83",
        "secondary-fixed-dim": "#77dd6a",
        "on-secondary-fixed": "#002201",
        "on-secondary-fixed-variant": "#005307",
        "tertiary-fixed": "#ffdbd1",
        "tertiary-fixed-dim": "#ffb5a0",
        "on-tertiary-fixed": "#3b0900",
        "on-tertiary-fixed-variant": "#872100",
        background: "#fbf9f8",
        "on-background": "#1b1c1c",
        "surface-variant": "#e4e2e1",
        "surface-alt": "#F7F9FA",
        "success-light": "#EBF7EB",
        "border-subtle": "#E2E8F0",
        "text-muted": "#64748B",
      },
      fontFamily: {
        "headline-lg": ["var(--font-hanken)"],
        "headline-lg-mobile": ["var(--font-hanken)"],
        "headline-md": ["var(--font-hanken)"],
        "body-lg": ["var(--font-inter)"],
        "body-md": ["var(--font-inter)"],
        "body-sm": ["var(--font-inter)"],
        "label-md": ["var(--font-inter)"],
        "label-sm": ["var(--font-inter)"],
      },
      fontSize: {
        "headline-lg": [
          "32px",
          { lineHeight: "40px", fontWeight: "700", letterSpacing: "-0.02em" },
        ],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", fontWeight: "700", letterSpacing: "-0.02em" },
        ],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-md": [
          "12px",
          { lineHeight: "16px", fontWeight: "600", letterSpacing: "0.05em" },
        ],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
      },
      borderRadius: {
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        gutter: "16px",
        "margin-desktop": "24px",
        "container-max-width": "1200px",
      },
      maxWidth: { "container-max-width": "1200px" },
    },
  },
};

export default config;
